# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(317, 197)
        Form.setMouseTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.arrangeBox = QtWidgets.QComboBox(Form)
        self.arrangeBox.setGeometry(QtCore.QRect(78, 22, 74, 20))
        self.arrangeBox.setObjectName("arrangeBox")
        self.arrangeBox.addItem("")
        self.arrangeBox.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(22, 22, 48, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(22, 53, 48, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(22, 87, 48, 16))
        self.label_3.setObjectName("label_3")
        self.alignHBox = QtWidgets.QComboBox(Form)
        self.alignHBox.setGeometry(QtCore.QRect(78, 54, 74, 20))
        self.alignHBox.setObjectName("alignHBox")
        self.alignHBox.addItem("")
        self.alignHBox.addItem("")
        self.alignHBox.addItem("")
        self.alignVBox = QtWidgets.QComboBox(Form)
        self.alignVBox.setGeometry(QtCore.QRect(78, 87, 74, 20))
        self.alignVBox.setObjectName("alignVBox")
        self.alignVBox.addItem("")
        self.alignVBox.addItem("")
        self.alignVBox.addItem("")
        self.generateBtn = QtWidgets.QPushButton(Form)
        self.generateBtn.setGeometry(QtCore.QRect(20, 120, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.generateBtn.setFont(font)
        self.generateBtn.setObjectName("generateBtn")
        self.inputBtn = QtWidgets.QPushButton(Form)
        self.inputBtn.setGeometry(QtCore.QRect(170, 53, 121, 23))
        self.inputBtn.setObjectName("inputBtn")
        self.outputBtn = QtWidgets.QPushButton(Form)
        self.outputBtn.setGeometry(QtCore.QRect(170, 86, 121, 23))
        self.outputBtn.setObjectName("outputBtn")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(170, 22, 121, 20))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_4 = QtWidgets.QLabel(self.splitter)
        self.label_4.setObjectName("label_4")
        self.paddingTxt = QtWidgets.QLineEdit(self.splitter)
        self.paddingTxt.setObjectName("paddingTxt")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 261, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 195, 281, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit.setPalette(palette)
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setFrame(False)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        self.arrangeBox.setCurrentIndex(0)
        self.alignHBox.setCurrentIndex(1)
        self.alignVBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LayaBox - 多态图工具"))
        self.arrangeBox.setItemText(0, _translate("Form", "水平方向"))
        self.arrangeBox.setItemText(1, _translate("Form", "垂直方向"))
        self.label.setText(_translate("Form", "图片方向"))
        self.label_2.setText(_translate("Form", "水平对齐"))
        self.label_3.setText(_translate("Form", "垂直对齐"))
        self.alignHBox.setItemText(0, _translate("Form", "靠左对齐"))
        self.alignHBox.setItemText(1, _translate("Form", "居中对齐"))
        self.alignHBox.setItemText(2, _translate("Form", "靠右对齐"))
        self.alignVBox.setItemText(0, _translate("Form", "顶部对齐"))
        self.alignVBox.setItemText(1, _translate("Form", "居中对齐"))
        self.alignVBox.setItemText(2, _translate("Form", "底部对齐"))
        self.generateBtn.setText(_translate("Form", "生成"))
        self.inputBtn.setText(_translate("Form", "打开输入文件夹"))
        self.outputBtn.setText(_translate("Form", "打开输出文件夹"))
        self.label_4.setText(_translate("Form", "边距( ±100 ) "))
        self.paddingTxt.setText(_translate("Form", "2"))
        self.label_5.setText(_translate("Form", "目前仅支持PNG格式 按图片命名降序排列"))
        self.lineEdit.setText(_translate("Form", "https://github.com/alpxe/laya-polymorhic-graph"))
